name: Cron jobs

on:
  #   schedule:
  #     - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["stagenet"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "moonbeam-foundation/moonbeam"
          path: mb
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Run smoke test
        # Set the ENV_WSS_NETWORK secret as an environment variable
        # copy config from this repo
        run: |
          cd mb/test
          cp ../../smoke/moonwall.config .
          bun install
          bun moonwall test smoke_${{ matrix.network }}

        # add upload to prod moonscope server
